{{- if not .Values.minecraftServer.rcon.existingSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ template "minecraft.fullname" . }}-rcon"
  labels:
    app: {{ template "minecraft.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  rcon-password: {{ default "" .Values.minecraftServer.rcon.password | b64enc | quote }}
{{- end }}
{{- if not .Values.minecraftServer.autoCurseForge.apiKey.existingSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ template "minecraft.fullname" . }}-curseforge"
  labels:
    app: {{ template "minecraft.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  cf-api-key: {{ default "" .Values.minecraftServer.autoCurseForge.apiKey.key | b64enc | quote }}
{{- end }}
